// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dte6EB-y9t1GqKZqGnRW74RCMIivFGU',
    appId: '1:270018592041:web:09193f7d1e3e9dc08d0b38',
    messagingSenderId: '270018592041',
    projectId: 'flutter-testing-alvin',
    authDomain: 'flutter-testing-alvin.firebaseapp.com',
    storageBucket: 'flutter-testing-alvin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHBqTEYHdBV3lnwPdVH44pwQv0JIz7jzw',
    appId: '1:270018592041:android:53d985f03a0a4dc28d0b38',
    messagingSenderId: '270018592041',
    projectId: 'flutter-testing-alvin',
    storageBucket: 'flutter-testing-alvin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqquWhCdxtUNito8YvII2qHjzhjIgf-Fg',
    appId: '1:270018592041:ios:a4018795a1ec38988d0b38',
    messagingSenderId: '270018592041',
    projectId: 'flutter-testing-alvin',
    storageBucket: 'flutter-testing-alvin.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestingApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqquWhCdxtUNito8YvII2qHjzhjIgf-Fg',
    appId: '1:270018592041:ios:a4018795a1ec38988d0b38',
    messagingSenderId: '270018592041',
    projectId: 'flutter-testing-alvin',
    storageBucket: 'flutter-testing-alvin.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestingApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1dte6EB-y9t1GqKZqGnRW74RCMIivFGU',
    appId: '1:270018592041:web:d3cb5e6927c50f7f8d0b38',
    messagingSenderId: '270018592041',
    projectId: 'flutter-testing-alvin',
    authDomain: 'flutter-testing-alvin.firebaseapp.com',
    storageBucket: 'flutter-testing-alvin.firebasestorage.app',
  );
}
